server:
  port: 7979

spring:
  profiles:
    active: dev
  application:
    name: cloud-gateway

swagger:
  title: cloud-gateway
  description: Parent pom providing dependency and plugin management for applications
		built with Maven